import { Router } from "express";
import {
  contributionCreateSchema,
  contributionUpdateSchema,
  contributionListQuery,
  type ContributionListQuery,
} from "@makthab/shared";
import { contributionRepository } from "../db";
import { asyncHandler } from "../lib/asyncHandler";
import { validateBody, validateQuery } from "../middleware/validate";
import { requireAuth, requireModuleAccessOrReportsView, requireResourcePermission } from "../middleware/auth";
import { AppError } from "../middleware/errorHandler";
import { actorStaffId } from "../lib/actor";
import { nextContributionReceiptNo } from "../lib/docNo";
import { renderPdf } from "../lib/pdf";
import { getOrgHeader } from "../lib/orgProfile";
import { MONTH_ABBR } from "../lib/monthNames";
import { buildWhatsAppLink, sendWhatsAppDocumentViaBusinessApi } from "../lib/whatsapp";
import { env } from "../lib/env";
import { getStorage, readStoredFile, normalizeStoredKey } from "../lib/storage";
import { logger } from "../lib/logger";
import { recordAuditFromRequest } from "../lib/audit/auditLog";

export const contributionsRouter = Router();

// Reads also allow reports.view — Reports can list contributions via this API
// (same pattern as /fees list). Mutations still require fees.create/update/delete.
contributionsRouter.use(requireAuth, requireModuleAccessOrReportsView("fees"));

type ContributionRow = NonNullable<Awaited<ReturnType<typeof contributionRepository.findById>>>;

function resolveContributorName(
  contributorType: string,
  contributorName: string | null | undefined
): string {
  const trimmed = contributorName?.trim() ?? "";
  if (contributorType === "anonymous") return trimmed || "Anonymous";
  return trimmed;
}

function formatReceiptDate(d: Date | string): string {
  const date = new Date(d);
  return `${String(date.getUTCDate()).padStart(2, "0")}-${MONTH_ABBR[date.getUTCMonth()]}-${date.getUTCFullYear()}`;
}

function contributorTypeLabel(type: string): string {
  return type === "anonymous" ? "Anonymous" : "Individual";
}

async function receiptPdf(row: ContributionRow): Promise<Buffer> {
  const org = await getOrgHeader();
  const lines: Array<string | [string, string]> = [
    ["Receipt No", row.receiptNo],
    ["Date", formatReceiptDate(row.date)],
    ["Contributor", row.contributorName],
    ["Type", contributorTypeLabel(row.contributorType)],
    ["Amount", `Rs. ${row.amount.toFixed(2)}`],
  ];
  if (row.notes) lines.push(["Notes", row.notes]);
  if (row.recordedBy) {
    lines.push(["Recorded by", `${row.recordedBy.fullName} (${row.recordedBy.role})`]);
  }
  lines.push("", "Thank you for your contribution. JazakAllah.");

  return renderPdf({
    org,
    title: "Contribution Receipt",
    lines,
    footer: "Generated by Makthab",
  });
}

async function saveReceiptPdf(receiptNo: string, pdf: Buffer): Promise<string> {
  const key = `receipts/${receiptNo}.pdf`;
  try {
    await getStorage().save(key, pdf, { contentType: "application/pdf" });
    return key;
  } catch (err) {
    logger.error(`failed to store contribution receipt ${key}: ${(err as Error).message}`);
    throw new AppError(500, "storage_error", "Failed to store receipt PDF");
  }
}

async function loadReceiptPdf(row: ContributionRow): Promise<Buffer> {
  if (row.pdfPath) {
    const stored = await readStoredFile(row.pdfPath);
    if (stored) return stored;
  }
  return receiptPdf(row);
}

async function deleteReceiptPdf(pdfPath: string | null): Promise<void> {
  if (!pdfPath) return;
  try {
    const key = normalizeStoredKey(pdfPath);
    await getStorage().delete(key);
  } catch (err) {
    logger.debug(`contribution receipt delete skipped for ${pdfPath}: ${(err as Error).message}`);
  }
}

// GET /contributions — list (optional year filter).
contributionsRouter.get(
  "/",
  validateQuery(contributionListQuery),
  asyncHandler(async (_req, res) => {
    const q = res.locals.query as ContributionListQuery;
    const { items, total, totalAmount } = await contributionRepository.list(q);
    res.json({ data: { items, total, page: q.page, limit: q.limit, totalAmount } });
  })
);

// POST /contributions — create + generate PDF + receiptNo.
contributionsRouter.post(
  "/",
  requireResourcePermission("fees", "create"),
  validateBody(contributionCreateSchema),
  asyncHandler(async (req, res) => {
    const dto = req.body as typeof contributionCreateSchema._output;
    const contributorName = resolveContributorName(dto.contributorType, dto.contributorName);
    const receiptNo = await nextContributionReceiptNo(dto.date);

    const created = await contributionRepository.create({
      amount: dto.amount,
      contributorName,
      contributorType: dto.contributorType,
      date: dto.date,
      receiptNo,
      notes: dto.notes ?? null,
      whatsappNo: dto.whatsappNo ?? null,
      recordedById: actorStaffId(req),
    });

    const pdfPath = await saveReceiptPdf(receiptNo, await receiptPdf(created));
    const row = await contributionRepository.setPdfPath(created.id, pdfPath);

    await recordAuditFromRequest(req, {
      action: "create",
      entity: "contribution",
      resourceId: row.id,
      outcome: "success",
      additionalDetails: {
        receiptNo,
        amount: dto.amount,
        contributorType: dto.contributorType,
      },
    });

    res.status(201).json({ data: row });
  })
);

// GET /contributions/:id
contributionsRouter.get(
  "/:id",
  asyncHandler(async (req, res) => {
    const row = await contributionRepository.findById(Number(req.params.id));
    if (!row) throw new AppError(404, "not_found", "Contribution not found");
    res.json({ data: row });
  })
);

// PATCH /contributions/:id — update (receiptNo immutable); regenerate PDF when content changes.
contributionsRouter.patch(
  "/:id",
  requireResourcePermission("fees", "update"),
  validateBody(contributionUpdateSchema),
  asyncHandler(async (req, res) => {
    const id = Number(req.params.id);
    const existing = await contributionRepository.findById(id);
    if (!existing) throw new AppError(404, "not_found", "Contribution not found");

    const dto = req.body as typeof contributionUpdateSchema._output;
    const contributorType = dto.contributorType ?? existing.contributorType;
    const nameSource =
      dto.contributorName !== undefined ? dto.contributorName : existing.contributorName;
    const contributorName =
      dto.contributorName !== undefined || dto.contributorType !== undefined
        ? resolveContributorName(contributorType, nameSource)
        : undefined;

    if (
      (dto.contributorName !== undefined || dto.contributorType !== undefined) &&
      contributorType === "individual" &&
      !contributorName
    ) {
      throw new AppError(
        400,
        "validation_error",
        "contributorName is required when contributorType is individual"
      );
    }

    const updated = await contributionRepository.update(id, {
      ...(dto.amount !== undefined ? { amount: dto.amount } : {}),
      ...(contributorName !== undefined ? { contributorName } : {}),
      ...(dto.contributorType !== undefined ? { contributorType: dto.contributorType } : {}),
      ...(dto.date !== undefined ? { date: dto.date } : {}),
      ...(dto.notes !== undefined ? { notes: dto.notes ?? null } : {}),
      ...(dto.whatsappNo !== undefined ? { whatsappNo: dto.whatsappNo ?? null } : {}),
    });

    const contentChanged =
      dto.amount !== undefined ||
      dto.contributorName !== undefined ||
      dto.contributorType !== undefined ||
      dto.date !== undefined ||
      dto.notes !== undefined;

    let row = updated;
    if (contentChanged) {
      const pdfPath = await saveReceiptPdf(updated.receiptNo, await receiptPdf(updated));
      row = await contributionRepository.setPdfPath(updated.id, pdfPath);
    }

    await recordAuditFromRequest(req, {
      action: "update",
      entity: "contribution",
      resourceId: row.id,
      outcome: "success",
      additionalDetails: { receiptNo: row.receiptNo },
    });

    res.json({ data: row });
  })
);

// DELETE /contributions/:id — hard-delete + best-effort PDF removal.
contributionsRouter.delete(
  "/:id",
  requireResourcePermission("fees", "delete"),
  asyncHandler(async (req, res) => {
    const id = Number(req.params.id);
    const existing = await contributionRepository.findById(id);
    if (!existing) throw new AppError(404, "not_found", "Contribution not found");

    await contributionRepository.delete(id);
    await deleteReceiptPdf(existing.pdfPath);

    await recordAuditFromRequest(req, {
      action: "delete",
      entity: "contribution",
      resourceId: id,
      outcome: "success",
      additionalDetails: { receiptNo: existing.receiptNo },
    });

    res.json({ data: { id } });
  })
);

// GET /contributions/:id/receipt — stream the receipt PDF.
contributionsRouter.get(
  "/:id/receipt",
  asyncHandler(async (req, res) => {
    const row = await contributionRepository.findById(Number(req.params.id));
    if (!row) throw new AppError(404, "not_found", "Contribution not found");
    const pdf = await loadReceiptPdf(row);
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `inline; filename="${row.receiptNo}.pdf"`);
    res.end(pdf);
  })
);

// POST /contributions/:id/whatsapp — mirror fees WhatsApp (walink / business-api).
contributionsRouter.post(
  "/:id/whatsapp",
  requireResourcePermission("fees", "update"),
  asyncHandler(async (req, res) => {
    const row = await contributionRepository.findById(Number(req.params.id));
    if (!row) throw new AppError(404, "not_found", "Contribution not found");
    if (row.whatsappSent) {
      throw new AppError(409, "already_sent", "Receipt already sent via WhatsApp");
    }
    if (!row.whatsappNo) {
      throw new AppError(400, "no_whatsapp_number", "Contribution has no WhatsApp number on file");
    }

    const caption =
      `Assalamu Alaikum. Contribution receipt ${row.receiptNo} from ${row.contributorName} ` +
      `(${contributorTypeLabel(row.contributorType)}): ` +
      `₹ ${row.amount.toFixed(2)}/- received on ${formatReceiptDate(row.date)}. JazakAllah.`;

    if (env.whatsappGateway === "business-api") {
      const pdf = await loadReceiptPdf(row);
      await sendWhatsAppDocumentViaBusinessApi(row.whatsappNo, pdf, `${row.receiptNo}.pdf`, caption);
      await contributionRepository.markWhatsappSent(row.id);
      res.json({ data: { mode: "business-api", whatsappSent: true } });
      return;
    }

    const link = buildWhatsAppLink(row.whatsappNo, caption);
    await contributionRepository.markWhatsappSent(row.id);
    res.json({ data: { mode: "walink", link, whatsappSent: true } });
  })
);
