// Generates server/prisma/sqlite/schema.prisma from the canonical
// server/prisma/schema.prisma (PostgreSQL). Run via:
//   npm run db:generate:sqlite-schema -w server
//
// Only the datasource provider and generator output path differ between the
// two schemas — Decimal-vs-Float type mapping is deferred (see
// docs/architecture/redesign/01-multi-database-support.md §2.2/§2.4), so
// every model is copied byte-for-byte.

import fs from "node:fs";
import path from "node:path";

const CANONICAL = path.resolve(__dirname, "schema.prisma");
const OUT = path.resolve(__dirname, "sqlite/schema.prisma");

const HEADER =
  "// AUTO-GENERATED by `npm run db:generate:sqlite-schema -w server`\n" +
  "// (server/prisma/generate-sqlite-schema.ts) from the canonical\n" +
  "// server/prisma/schema.prisma. DO NOT EDIT BY HAND — re-run the generator.\n" +
  "// Only the datasource provider and generator output path differ from the\n" +
  "// canonical Postgres schema (Decimal conversion is deferred — see\n" +
  "// docs/architecture/redesign/01-multi-database-support.md §2.2/§2.4).\n\n";

function transform(src: string): string {
  const out = src
    .replace(
      /datasource\s+db\s*\{[^}]*\}/s,
      'datasource db {\n  provider = "sqlite"\n  url      = env("DATABASE_URL")\n}'
    )
    .replace(
      /generator\s+client\s*\{[^}]*\}/s,
      'generator client {\n  provider = "prisma-client-js"\n  output   = "../generated/sqlite-client"\n}'
    );

  // Defensive self-check: nothing "postgresql" should remain outside the
  // (already-replaced) datasource block — catches a silently-no-op regex.
  if (/provider\s*=\s*"postgresql"/.test(out)) {
    throw new Error("generate-sqlite-schema: datasource block was not rewritten — aborting.");
  }
  return HEADER + out;
}

const source = fs.readFileSync(CANONICAL, "utf8");
fs.writeFileSync(OUT, transform(source));
console.log(`Generated ${path.relative(process.cwd(), OUT)} from ${path.relative(process.cwd(), CANONICAL)}`);
